version: "3.8"
services:

#  order-service:
#    build:
#      context: ./order-service
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mariadb
#      - postgres

#  mongodb:
#    image: 'mongo:6.0'
#    environment:
#      - 'MONGO_INITDB_DATABASE=mydatabase'
#    ports:
#      - '27019:27017'
#    volumes:
#      - ./data:/data/db

  postgres:
    image: 'postgres:15'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5433:5432'

  mariadb:
    image: mariadb:11.0-rc
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=springbootdb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_INITDB_ADDITIONAL_GRANT_PRIVILEGES=ALL PRIVILEGES ON *.* TO 'myuser'@'%' WITH GRANT OPTION
    ports:
      - 3310:3306
    volumes:
      - ./data:/var/lib/mysql

